name: Register Credential Template

trigger:
  type: api

actions:
  # Create a schema (template) for the credential you would like to issue
  - id: createSchema
    name: anoncreds/createSchema@v1
    attributes:
      attributeNames:
        - name
        - email
      name: Bank Account credential
      version: '1.0'
      network: cheqd:testnet

  # Bind the schema by creating a credential definition
  - id: createCredentialDefinition
    name: anoncreds/createCredentialDefinition@v1
    attributes:
      schemaId: $.actions.createSchema.output.schemaId
      tag: Bank Account credential
